"""Public API for the authoring feature."""
from . import composition, composition_model, artifact001_layouts
from .composition import (
    ENGINE_VERSION,
    SCHEMA_VERSION,
    ORIENTATIONS,
    RNG,
    StateError,
    load_state,
    save_state,
    validate_state,
    validate_audio,
    resolve_at,
    pixel_placements,
    from_authoring_model,
    sha256_file,
    render_from_args,
)
from .composition_model import (
    Composition,
    LoopState,
    Layout,
    Placement,
    SilentAudio,
    SoundtrackAudio,
    SpatialLoopsAudio,
)
from .artifact001_layouts import (
    build_artifact001,
    AUTHORED,
)

__all__ = [
    'composition',
    'composition_model',
    'artifact001_layouts',
    'ENGINE_VERSION',
    'SCHEMA_VERSION',
    'ORIENTATIONS',
    'RNG',
    'StateError',
    'load_state',
    'save_state',
    'validate_state',
    'validate_audio',
    'resolve_at',
    'pixel_placements',
    'from_authoring_model',
    'sha256_file',
    'render_from_args',
    'Composition',
    'LoopState',
    'Layout',
    'Placement',
    'SilentAudio',
    'SoundtrackAudio',
    'SpatialLoopsAudio',
    'build_artifact001',
    'AUTHORED',
]
